# https://squidfunk.github.io/mkdocs-material/getting-started

site_name: Emonoda
site_description: Система управления коллекцией торрентов
site_author: Maxim Devaev
site_url: https://mdevaev.github.io/emonoda

repo_name: mdevaev/emonoda
repo_url: https://github.com/mdevaev/emonoda

copyright: "Copyright &copy; 2018 Maxim Devaev"

theme:
    name: material
    language: ru
    custom_dir: docs/theme
    feature:
        tabs: false
    palette:
        primary: blue grey
        accent: pink

plugins:
  - search:
      lang:
        - ru

extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/mdevaev/emonoda
    search:
        language: "en, ru"

markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: docs

nav:
    - "Emonoda -- 得物だ": index.md
    - "Настройка":
        - "Общие принципы настройки": config.md
        - "Настройка интеграции с торрент-клиентом": clients.md
        - "Настройка трекеров": trackers.md
        - "Настройка оповещений об обновлениях": confetti.md
    - "Команды":
        - "emupdate": emupdate.md
        - "emfile": emfile.md
        - "emdiff": emdiff.md
        - "emload": emload.md
        - "emrm": emrm.md
        - "emfind": emfind.md
        - "emconfetti-demo": emconfetti-demo.md
        - "emconfetti-tghi": emconfetti-tghi.md
    - "Спецкостыли для клиентов": hooks.md
    - "Инфа для разработчиков":
        - "rTorrent XMLRPC Reference": rTorrent-XMLRPC-Reference.md
        - "rTorrent system_multicall": rTorrent-system_multicall.md
